# Generated by Django 4.2.7 on 2023-11-26 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VolcanesChile', '0002_alter_clasificacion_alturacolumna'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos',
            new_name='Producto',
        ),
    ]
