# Generated by Django 4.2.7 on 2023-11-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VolcanesChile', '0003_rename_productos_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='alcance',
            field=models.IntegerField(max_length=20),
        ),
    ]
