# Generated by Django 4.2.7 on 2023-11-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VolcanesChile', '0004_alter_producto_alcance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='alcance',
            field=models.CharField(max_length=20),
        ),
    ]
